apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sdgsocialdemo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demologin
spec:
  hosts:
  - "*"
  gateways:
  - sdgsocialdemo-gateway
  http:
  - match:
    - uri:
        prefix: /v1/api/demo
    route:
    - destination:
        host: demologin
        port:
          number: 9080